"""
Django settings for swapanalyser project.
Generated by 'django-admin startproject' using Django 4.2.29.
"""

from pathlib import Path
import os
import dj_database_url

# 1. Import Environment Variables (Local Dev)
if os.path.isfile("env.py"):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CORE CONFIGURATION ---

# SECRET_KEY:
# Tries to get the real key. Falls back to a dummy key locally so 'runserver' doesn't crash.
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-dev-key-placeholder"
)

# DEBUG:
# Checks if 'DEVELOPMENT' exists in env. If yes -> True (Local). If no -> False (Production).
DEBUG = "DEVELOPMENT" in os.environ
DEVELOPMENT = "DEVELOPMENT" in os.environ

ALLOWED_HOSTS = [
    ".herokuapp.com",
    "127.0.0.1",
    "localhost",
]

# Heroku app URL
CSRF_TRUSTED_ORIGINS = [
    "https://project-swaps-app-52891839a6f0.herokuapp.com",
    "https://*.herokuapp.com"
]


# --- SECURITY: PRODUCTION SETTINGS ---
# This block ONLY runs on Heroku/Live (when DEBUG is False).

if not DEBUG:
    # 1. Force HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    # 2. Secure Cookies 
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 3. HSTS (Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000 
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    # Third Party
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "crispy_forms",
    "crispy_bootstrap5",
    # Local Apps
    "workspace.apps.WorkspaceConfig",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

SITE_ID = 1
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "swapanalyser.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "swapanalyser.wsgi.application"


# --- DATABASE CONFIGURATION ---

# Robust Setup:
# 1. Use DATABASE_URL if available (Heroku/Postgres).
# 2. Fallback to SQLite if missing (Local/Testing).
if "DATABASE_URL" in os.environ:
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# --- PASSWORD VALIDATION ---

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# --- ACCOUNT CONFIGURATION (ALLAUTH) ---

# 1. Login Method
ACCOUNT_LOGIN_METHODS = {'email'}

# 2. Signup Fields

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "first_name",
    "last_name",
]

# 3. Email Uniqueness
ACCOUNT_UNIQUE_EMAIL = True

# 4. Verification Logic

if not DEBUG:
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 
    ACCOUNT_EMAIL_REQUIRED = True
    ACCOUNT_LOGIN_ON_SIGNUP = True 
    ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
    ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
    ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

# FORCE BYPASS FOR UI TESTING
# ACCOUNT_EMAIL_VERIFICATION = 'none'
# ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow username login to bypass MFA
# ACCOUNT_SIGNUP_FIELDS = ["email*", "first_name", "last_name"]
# ACCOUNT_LOGIN_ON_SIGNUP = True
# ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True

# Disable the specific "Sign-in by Code" feature
ACCOUNT_SIGNIN_BY_CODE_ENABLED = False 


# --- INTERNATIONALISATION ---

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# --- STATIC FILES ---

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# --- DEFAULT FIELD ---

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- STRIPE CONFIGURATION ---

STRIPE_PUBLIC_KEY = os.environ.get("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")
STRIPE_PRICE_ID = os.environ.get("STRIPE_PRICE_ID")
STRIPE_WH_SECRET = os.getenv("STRIPE_WH_SECRET")


# --- EMAIL CONFIGURATION ---

if DEBUG:
    # Local: Print emails to console (Terminals)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "terminal@irsquant.io"
else:
    # Production: Use Gmail/SMTP with SSL
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 465           # Changed from 587
    EMAIL_USE_SSL = True       
    EMAIL_USE_TLS = False      
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASS")
    DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_HOST_USER")
