# Generated by Django 6.0.3 on 2026-03-06 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('index_name', models.CharField(choices=[('SOFR', 'USD SOFR'), ('SONIA', 'GBP SONIA'), ('EURIBOR', 'EUR EURIBOR'), ('ESTR', 'EUR €STR'), ('TONA', 'JPY TONA'), ('TIBOR', 'JPY TIBOR'), ('SARON', 'CHF SARON'), ('JIBAR', 'ZAR JIBAR'), ('WIBOR', 'PLN WIBOR')], max_length=10)),
                ('tenor', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
            ],
            options={
                'ordering': ['-date', 'index_name'],
                'unique_together': {('date', 'index_name', 'tenor')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('OUTRIGHT', 'Outright'), ('FLY', 'Butterfly')], default='OUTRIGHT', max_length=10)),
                ('group_id', models.CharField(blank=True, help_text='Links Butterfly legs', max_length=50, null=True)),
                ('ticker', models.CharField(max_length=20)),
                ('notional', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenor_years', models.PositiveIntegerField()),
                ('fixed_rate', models.FloatField()),
                ('side', models.CharField(choices=[('PAY', 'Pay Fixed'), ('REC', 'Rec Fixed')], max_length=3)),
                ('weight', models.FloatField(default=1.0)),
                ('last_npv', models.FloatField(blank=True, null=True)),
                ('pv01', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
