# Generated by Django 6.0.3 on 2026-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='TEMP-001', help_text='Custom Trade ID (e.g. TRD-001)', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
