# Generated by Django 6.0.3 on 2026-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_trade_trade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="forward_start",
            field=models.FloatField(
                blank=True, default=0.0, verbose_name="Start Delay (Years)"
            ),
        ),
    ]
