# Generated by Django 6.0.3 on 2026-04-23 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_alter_trade_fixed_rate_alter_trade_notional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="forward_start",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Start Delay (Years)",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="notional",
            field=models.DecimalField(
                decimal_places=2,
                default=10000000,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="ticker",
            field=models.CharField(
                choices=[
                    ("SOFR", "USD SOFR"),
                    ("SONIA", "GBP SONIA"),
                    ("EURIBOR", "EUR EURIBOR"),
                    ("ESTR", "EUR €STR"),
                    ("TONA", "JPY TONA"),
                    ("TIBOR", "JPY TIBOR"),
                    ("SARON", "CHF SARON"),
                    ("JIBAR", "ZAR JIBAR"),
                    ("WIBOR", "PLN WIBOR"),
                ],
                default="SOFR",
                max_length=20,
            ),
        ),
    ]
